import { SidebarItemConfig } from "@site/sidebars/types";
import {
  cat,
  docsClassCat,
} from "../../../common";

const sidebar: SidebarItemConfig = docsClassCat("string", "std/containers/strings/string", "", [
  "constructors",
  "op:operator_assign",
  "m:assign",
  "m:get_allocator",
  cat("Element access"),
  "m:at",
  "op:operator_subscript",
  ["m:front", "since-cpp11"],
  ["m:back", "since-cpp11"],
  "m:data",
  "m:c_str",
  ["op:operator_string_view", "since-cpp23"],
  cat("Iterators"),
  ["op:begin", "since-cpp11"],
  ["op:end", "since-cpp11"],
  ["op:rbegin", "since-cpp11"],
  ["op:rend", "since-cpp11"],
  cat("Capacity"),
  "m:empty",
  "m:size",
  "m:max_size",
  "m:reserve",
  "m:capacity",
  ["shrink_to_fit", "since-cpp11"],
  cat("Operations"),
  "m:clear",
  "m:insert",
  "m:erase",
  "m:push_back",
  ["m:pop_back", "since-cpp11"],
  "m:append",
  "op:operator_addeq",
  "m:compare",
  ["m:starts_with", "since-cpp20"],
  ["m:ends_with", "since-cpp20"],
  ["m:contains", "since-cpp23"],
  "m:replace",
  "m:substr",
  "m:copy",
  "m:resize",
  ["m:resize_and_overwrite", "since-cpp23"],
  "m:swap",
  cat("Search"),
  "m:find",
  "m:rfind",
  "m:find_first_of",
  "m:find_first_not_of",
  "m:find_last_of",
  "m:find_last_not_of",
]);

export default sidebar;